feat: switch storage provider
teknologi-umum/pesto pull request #53
Opened 2022-10-01 09:50 UTC by aldy505

Closes #52

2022-10-02 08:07 UTC, RayWP requested changes

2022-10-02 08:07 UTC, RayWP commented on docker-compose.yml
> +      - "--metrics.prometheus.ent`ryPoint=metrics"
Ini entrynya emang ada ` ya?

2022-10-03 10:27 UTC, elianiva requested changes

2022-10-03 10:27 UTC, elianiva commented on registration/Controllers/RegistrationController.cs
> +        var waitingList = await _waitingListService.GetUsersAsync(CancellationToken.None);
ngga pake `CancellationToken` dari requestnya?

2022-10-03 10:27 UTC, elianiva commented on registration/Controllers/RegistrationController.cs
> +            select x).FirstOrDefault();
```suggestion
        var user = (from x in waitingList
                    where x.Email.Equals(userToken.Email)
                    select x).FirstOrDefault();

```

2022-10-03 10:27 UTC, elianiva commented on registration/Controllers/RegistrationController.cs
> +        }
```suggestion
        if (user is null) return BadRequest("Email does not exists");

```

2022-10-03 10:27 UTC, elianiva commented on registration/Services/ApprovalService.cs
> +        if (user == null) throw new UserNotExistsException(token);
```suggestion
        if (user is null) throw new UserNotExistsException(token); 

```

2022-10-03 10:27 UTC, elianiva commented on registration/Services/EmailExistsException.cs
> +    }
```suggestion
    public EmailExistsException(string message)
        : base(message)
    {
    }

```

2022-10-03 10:27 UTC, elianiva commented on registration/Services/UserNotExistsException.cs
> +    }
```suggestion
    public UserNotExistsException(string message)
        : base(message)
    {
    } 

```

2022-10-03 10:27 UTC, elianiva commented on registration/Services/UserNotExistsException.cs
> +    }
```suggestion
    public UserNotExistsException(string message)
        : base(message)
    {
    } 

```

2022-10-03 10:27 UTC, elianiva commented on registration/Services/WaitingListService.cs
> +            .FirstOrDefault(false);
ngga pake `Enumerable.Any` aja?

2022-10-03 10:27 UTC, elianiva commented on registration/Services/WaitingListService.cs
> +        }
kalo gini aja bisa ngga?

```suggestion
        var users = waitingList
            .Where(user => user.HasValue)
            .Select(user => JsonSerializer.Deserialize<User>(user.ToString()))
            .Where(user => user is not null)
            .ToList();
```

2022-10-03 10:27 UTC, elianiva commented on registration/Services/WaitingListService.cs
> +            select waitingListUser;
filter + serializenya pindahin kesini aja coba

```suggestion
        var filteredWaitingListUsers = from waitingListUser in waitingListUsers
                                       where waitingListUser is not null && waitingListUser.Email != user.Email
                                       select JsonSerializer.Serialize(waitingListUser);

```

2022-10-03 10:27 UTC, elianiva commented on registration/Services/WaitingListService.cs
> +        }
biar disini tinggal insert

```suggestion
        foreach (var value in filteredWaitingListUsers)
        {
            await db.ListRightPushAsync("waiting-list", serializedUser);
        }
```

2022-10-03 10:36 UTC, aldy505 commented on registration/Controllers/RegistrationController.cs
> +        _approvalService = new ApprovalService(_redis);
iya

2022-10-03 10:36 UTC, aldy505 commented on registration/Controllers/RegistrationController.cs
> +            select x).FirstOrDefault();
ga commit ah biar lu kesel~

2022-10-08 04:41 UTC, elianiva approved these changes

2022-10-11 22:37 UTC, RayWP approved these changes

2022-10-12 00:34 UTC, merged